channels:
  - numba
  - conda-forge
dependencies:
  - python>=3.9
  - numpy>=1.22
  - scipy>=1.10
  - numba>=0.59.1
  - fftw
  - pyfftw
  - panel
  - pandas>=0.20.0
  - flake8>=3.7.7
  - black>=22.1.0
  - jupyterlab>=3.0
  - matplotlib>=3.3.0
  - pytest>=4.4.1
  - coverage>=4.5.3
